name: Build IntelliJ Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - uses: actions/checkout@v4

      # 2. Set up a JDK (11+)
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      # 3. Build the plugin ZIP
      - name: Build plugin
        run: ./gradlew clean buildPlugin --no-daemon

      # 4. Upload the ZIP so you can download it from the Actions page
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: copyforllm-plugin
          path: build/distributions/*.zip
