name: Build IntelliJ Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ← add this:
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Build plugin
        run: ./gradlew clean buildPlugin --no-daemon

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: copyforllm-plus-plugin
          path: build/distributions/*.zip
